name: Delete branch after merge

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Determine branch to delete
        id: get_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Delete branch
        if: |
          github.event.pull_request.head.ref == 'main' ||
          github.event.pull_request.head.ref == 'dev' ||
          github.event.pull_request.head.ref == 'staging' ||
          github.event.pull_request.head.ref == 'base'
        run: echo "Branch is protected, not deleting."

      - name: Delete branch
        if: |
          github.event.pull_request.head.ref != 'main' &&
          github.event.pull_request.head.ref != 'dev' &&
          github.event.pull_request.head.ref != 'staging' &&
          github.event.pull_request.head.ref != 'base'
        run: |
          git push origin --delete ${{ github.head_ref }}